import AgentCore

/-! Final designated strengthened claims. Representation component-shape nonclaims are excluded. -/

-- Complete structural Invocation identity.
#print axioms AgentCore.InvocationPayload.arguments_nonempty
#print axioms AgentCore.invocationDigest_exact
#print axioms AgentCore.structuralDigest_exact
#print axioms AgentCore.principal_ref_tenant_is_identity
#print axioms AgentCore.AuthorityLedger.acts_under_principal_is_tenant_qualified
#print axioms AgentCore.prepared_item_key_is_derived
#print axioms AgentCore.prepared_item_key_commits_complete_structure
#print axioms AgentCore.replay_preserves_item_order_and_keys

-- Canonical authority, containment, path ordering, and holder deadlines.
#print axioms AgentCore.AuthorityLedger.deny_overrides
#print axioms AgentCore.AuthorityLedger.authorized_binding_matches_operation_facet
#print axioms AgentCore.AuthorityLedger.resolution_issue_records_authorized_evidence
#print axioms AgentCore.AuthorityLedger.bump_scope_stales_path_evidence
#print axioms AgentCore.AuthorityLedger.delegated_allow_is_contained_and_not_wider
#print axioms AgentCore.AuthorityLedger.direct_deadline_cannot_exceed_original_lease
#print axioms AgentCore.AuthorityLedger.holder_observation_joins_epoch
#print axioms AgentCore.AuthorityLedger.direct_holder_watermark_is_not_ahead
#print axioms AgentCore.guest_allow_is_attenuated
#print axioms AgentCore.guest_deny_is_preserved
#print axioms AgentCore.rematerialization_advances_epoch

-- SPEC placement order, the §7.2 tier floor, and source assertion rejection.
-- Interceptor pipeline: total deterministic order, attribution, blocks, replay,
-- authority, and the mediated-tier raise.
#print axioms AgentCore.interceptor_order_total
#print axioms AgentCore.ordered_schedule_unique
#print axioms AgentCore.intercept_step_deterministic
#print axioms AgentCore.interception_outcome_deterministic
#print axioms AgentCore.run_records_transformation_chain
#print axioms AgentCore.lastRewrite_is_final
#print axioms AgentCore.run_attributes_last_rewriter
#print axioms AgentCore.run_rewritten_value_names_last_rewriter
#print axioms AgentCore.run_consumes_schedule_in_order
#print axioms AgentCore.completed_trace_records_schedule_order
#print axioms AgentCore.blocked_names_exact_scheduled_interceptor
#print axioms AgentCore.blocked_pipeline_never_completes
#print axioms AgentCore.replay_matches_chain
#print axioms AgentCore.interception_replay_deterministic
#print axioms AgentCore.run_replay_reproduces_result
#print axioms AgentCore.replay_refuses_exactly_broken_chains
#print axioms AgentCore.replay_item_reuses_persisted_transformations
#print axioms AgentCore.completed_runs_assemble_valid_replay_item
#print axioms AgentCore.cross_domain_interception_rejected
#print axioms AgentCore.undeclared_cross_facet_interception_rejected
#print axioms AgentCore.ungranted_cross_facet_interception_rejected
#print axioms AgentCore.run_trace_is_admitted
#print axioms AgentCore.unauthorized_interceptor_never_attributed
#print axioms AgentCore.interception_raises_direct_floor
#print axioms AgentCore.direct_admission_has_no_applicable_interceptor
#print axioms AgentCore.applicable_interceptor_forbids_direct_admission

-- SPEC placement order, mediated execute boundary, and source assertion rejection.
#print axioms AgentCore.placement_prefers_dynamic
#print axioms AgentCore.placement_uses_provider_without_dynamic
#print axioms AgentCore.placement_uses_bundled_last
#print axioms AgentCore.empty_intersection_rejects
#print axioms AgentCore.source_asserted_tier_rejected
#print axioms AgentCore.turn_owned_session_execute_floor_is_direct
#print axioms AgentCore.unowned_execute_floor_is_mediated
#print axioms AgentCore.direct_execute_requires_bundled_colocation

-- SecretRef custody (SPEC §3.5): exact tenant/Binding/endpoint resolution, repointing
-- invalidation, and carriers that hold refs, never raw values.
#print axioms AgentCore.secret_resolution_requires_exact_tenant
#print axioms AgentCore.foreign_tenant_secret_resolution_rejected
#print axioms AgentCore.secret_resolution_requires_current_custody
#print axioms AgentCore.mismatched_custody_secret_resolution_rejected
#print axioms AgentCore.fresh_resolution_is_current
#print axioms AgentCore.repoint_invalidates_prior_resolution
#print axioms AgentCore.boot_carriers_ref_only
#print axioms AgentCore.secret_step_preserves_carrier_ref_only
#print axioms AgentCore.reachable_carriers_ref_only
#print axioms AgentCore.secret_value_carrier_is_unreachable
#print axioms AgentCore.guest_grant_value_carrier_is_unreachable
#print axioms AgentCore.cross_tenant_reservation_value_carrier_is_unreachable

-- ContentStore custody (SPEC §8.2, C13-CONTENT-CUSTODY): tenant-bound resolution and
-- unowned-only collection, reachably.
#print axioms AgentCore.boot_owned_implies_stored
#print axioms AgentCore.content_resolution_requires_home_or_grant
#print axioms AgentCore.foreign_tenant_content_resolution_rejected
#print axioms AgentCore.missing_content_resolution_rejected
#print axioms AgentCore.collect_requires_unowned
#print axioms AgentCore.owned_content_cannot_be_collected
#print axioms AgentCore.content_step_preserves_owned_implies_stored
#print axioms AgentCore.reachable_owned_implies_stored
#print axioms AgentCore.collected_owned_content_is_unreachable

-- Blueprint materializer idempotence for Subscriptions (SPEC §9.3).
#print axioms AgentCore.materialize_registers_exact_subscription
#print axioms AgentCore.already_materialized_template_cannot_rematerialize
#print axioms AgentCore.reconcile_is_stored_identity
#print axioms AgentCore.materialize_step_preserves_installed_mapping
#print axioms AgentCore.materialized_automation_has_unique_firing_subscription

-- Environment Sessions: Turn-owned use, fail-closed lifecycle, credential isolation.
#print axioms AgentCore.session_use_is_turn_owned_and_live
#print axioms AgentCore.stale_session_admits_nothing
#print axioms AgentCore.close_disposes_child_facets
#print axioms AgentCore.closed_session_is_terminal
#print axioms AgentCore.rotation_does_not_retarget_open_sessions
#print axioms AgentCore.open_session_pins_current_revision
#print axioms AgentCore.session_pin_is_immutable
#print axioms AgentCore.session_egress_is_explicitly_bound
#print axioms AgentCore.unbound_send_is_refused
#print axioms AgentCore.proxy_send_writes_no_session_state
#print axioms AgentCore.env_step_preserves_credential_isolation
#print axioms AgentCore.reachable_credential_isolation
#print axioms AgentCore.plaintext_in_session_state_is_unreachable
#print axioms AgentCore.preview_ingress_is_exactly_the_exposed_port
#print axioms AgentCore.revoked_exposure_admits_no_ingress
#print axioms AgentCore.stale_exposure_admits_no_ingress

-- Slate and the dynamic isolate: explicit capability provenance, immutable records.
#print axioms AgentCore.fresh_dynamic_isolate_admits_only_host_pass
#print axioms AgentCore.isolate_invoke_requires_passed_binding
#print axioms AgentCore.isolate_egress_matches_passed_destination
#print axioms AgentCore.isolate_capability_growth_is_host_pass
#print axioms AgentCore.reachable_isolate_actions_are_binding_backed
#print axioms AgentCore.dynamic_only_manifest_never_places_ambient
#print axioms AgentCore.committed_version_is_immutable
#print axioms AgentCore.publication_is_immutable
#print axioms AgentCore.rollback_retargets_only_owned_successful_deployment
#print axioms AgentCore.provider_contact_only_from_deploy
#print axioms AgentCore.preview_is_live_environment_session

-- Exact Turn lease incarnation.
#print axioms AgentCore.lease_turn_immutable
#print axioms AgentCore.reclaim_requires_expiry
#print axioms AgentCore.resume_is_same_turn
#print axioms AgentCore.terminal_fence_is_atomic
#print axioms AgentCore.wrong_turn_rejects
#print axioms AgentCore.stale_token_rejects
#print axioms AgentCore.expired_lease_rejects
#print axioms AgentCore.renewal_cannot_extend_resolution_deadline

-- Exact Approval identity and persisted start.
#print axioms AgentCore.approval_available_is_exact
#print axioms AgentCore.approval_available_binds_authority_principal
#print axioms AgentCore.consumed_approval_unavailable
#print axioms AgentCore.approval_start_consumes_persisted_exact_intent
#print axioms AgentCore.approval_continuation_is_exact
#print axioms AgentCore.approval_continuation_validates_persisted_exact_intent
#print axioms AgentCore.approval_is_unique_per_invocation
#print axioms AgentCore.approval_available_has_no_continuation
#print axioms AgentCore.malformed_first_attempt_cannot_continue

-- Item attempts, current receipts, retry, supersession, and derived batch outcomes.
#print axioms AgentCore.retry_requires_prior_final_failure
#print axioms AgentCore.first_attempt_uses_exact_current_claim
#print axioms AgentCore.retry_uses_exact_current_claim_and_advances_ordinal
#print axioms AgentCore.claim_records_future_expiry
#print axioms AgentCore.claim_uses_exact_prepared_owner
#print axioms AgentCore.abandoned_claim_recovery_preserves_ordinal_without_attempt
#print axioms AgentCore.first_attempt_receipt_clears_only_final_claim
#print axioms AgentCore.superseding_final_receipt_clears_claim
#print axioms AgentCore.supersession_is_same_attempt_once
#print axioms AgentCore.supersession_at_most_once
#print axioms AgentCore.effect_step_preserves_receipt_id_disjointness
#print axioms AgentCore.pre_receipt_id_cannot_be_reused_for_attempt
#print axioms AgentCore.mixed_terminal_batch_is_partial
#print axioms AgentCore.indeterminate_batch_is_current_not_terminal
#print axioms AgentCore.terminal_batch_is_derived_not_stored

-- Lease-backed trust and route projection boundary.
#print axioms AgentCore.accepted_self_has_live_exact_lease
#print axioms AgentCore.stale_or_fabricated_token_cannot_self
#print axioms AgentCore.published_event_has_no_asserted_tier
#print axioms AgentCore.asserted_tier_publish_rejected
#print axioms AgentCore.target_projection_is_exact_authenticated_reservation_projection

-- Route reservation uniqueness and delivery dedupe (§14).
#print axioms AgentCore.default_reservation_for_consistent
#print axioms AgentCore.event_step_preserves_reservation_for_consistency
#print axioms AgentCore.reachable_reservation_for_consistent
#print axioms AgentCore.route_reservation_is_unique_per_invocation
#print axioms AgentCore.event_step_preserves_deliveries
#print axioms AgentCore.delivered_reservation_cannot_redeliver

-- Actor-local, ordered, typed audit.
#print axioms AgentCore.audit_sequence_is_unique
#print axioms AgentCore.local_cause_same_actor_lower_sequence
#print axioms AgentCore.local_cause_edge_is_typed
#print axioms AgentCore.projection_uses_reservation_bridge_not_source_audit
#print axioms AgentCore.audit_append_is_locally_acyclic
#print axioms AgentCore.audit_step_establishes_causal_chain
#print axioms AgentCore.causal_chain_preserved_by_step
#print axioms AgentCore.nonroot_cannot_append_without_cause
#print axioms AgentCore.every_audited_effect_evidence_matches
#print axioms AgentCore.delivery_audit_can_cause_commit_locally

-- Pinned graph writers, equal current heads, delivery, synthesis, and terminal snapshot.
#print axioms AgentCore.unary_commit_inherits_pins
#print axioms AgentCore.merge_has_equal_pinned_current_heads
#print axioms AgentCore.terminal_snapshot_is_coherent
#print axioms AgentCore.terminal_snapshot_captures_complete_frontier
#print axioms AgentCore.environment_pin_identity_prevents_revision_alias
#print axioms AgentCore.forced_cancellation_is_system_fence
#print axioms AgentCore.terminalization_requires_current_turn_pins
#print axioms AgentCore.migrated_old_turn_cannot_terminalize
#print axioms AgentCore.reserved_obligation_is_in_registry
#print axioms AgentCore.reserved_obligation_yields_valid_reservation
#print axioms AgentCore.terminalization_closes_exact_registry
#print axioms AgentCore.completed_obligation_is_reserved
#print axioms AgentCore.terminal_snapshot_has_no_omission_or_extra
#print axioms AgentCore.migration_requires_valid_target_pins
#print axioms AgentCore.spawn_child_requires_fresh_branch_and_root
#print axioms AgentCore.migration_requires_fresh_commit_on_owned_branch
#print axioms AgentCore.spawn_child_rejects_existing_root
#print axioms AgentCore.migration_rejects_existing_commit
#print axioms AgentCore.terminalization_requires_terminal_and_unheld_siblings
#print axioms AgentCore.delivery_commit_matches_route
#print axioms AgentCore.system_control_writer_uses_exact_typed_audit
#print axioms AgentCore.synthesis_is_system_controlled_exact_turn

-- Undo as append-only selection, fenced before it may append.
#print axioms AgentCore.undo_requires_unheld_branch_and_ancestor_selection
#print axioms AgentCore.undo_fences_held_turn
#print axioms AgentCore.expired_lease_still_holds_branch
#print axioms AgentCore.forced_cancellation_unblocks_undo
#print axioms AgentCore.graph_step_preserves_commits
#print axioms AgentCore.graph_reachable_preserves_commits
#print axioms AgentCore.ancestor_preserved_by_commit_growth
#print axioms AgentCore.undo_keeps_prior_head_reachable
#print axioms AgentCore.undo_selects_effective_state
#print axioms AgentCore.undo_then_redo_restores_effective_state

-- Split direct and mediated composition plus derived settlement.
#print axioms AgentCore.direct_admission_is_nondurable
#print axioms AgentCore.direct_checks_exact_current_incarnation
#print axioms AgentCore.exact_turn_lease_gate_binds_run_domain_and_placement
#print axioms AgentCore.direct_resolution_uses_actual_lease_expiry
#print axioms AgentCore.direct_ready_uses_exact_holder_watermark_inequality
#print axioms AgentCore.mediated_without_turn_uses_owning_actor_path
#print axioms AgentCore.mediated_without_turn_has_exact_owner_audit
#print axioms AgentCore.mediated_ready_validates_exact_run_reservation
#print axioms AgentCore.mediated_ready_reserves_exact_obligation
#print axioms AgentCore.changed_registry_epoch_blocks_mediated_ready
#print axioms AgentCore.approval_admission_requires_reserved_obligation
#print axioms AgentCore.item_claim_requires_reserved_obligation
#print axioms AgentCore.approved_effect_admission_requires_reserved_item
#print axioms AgentCore.continued_effect_admission_requires_reserved_item
#print axioms AgentCore.routed_mediated_validates_projection_digest
#print axioms AgentCore.routed_reservation_binds_source_event_audit
#print axioms AgentCore.stale_mediated_denial_matches_intent
#print axioms AgentCore.settled_has_coherent_snapshot_and_exact_obligations
#print axioms AgentCore.item_obligation_uses_exact_audit
#print axioms AgentCore.acceptance_unsatisfied_not_settled
#print axioms AgentCore.acceptance_verdict_only_for_its_subject
#print axioms AgentCore.acceptance_current_verdict_blocks_retry
#print axioms AgentCore.verifier_receipt_is_functional
#print axioms AgentCore.generic_reservation_refuses_acceptance
#print axioms AgentCore.generic_completion_refuses_acceptance
#print axioms AgentCore.run_start_reserves_exactly_declared_acceptance
#print axioms AgentCore.spawn_child_reserves_exactly_declared_acceptance
#print axioms AgentCore.acceptance_verdict_step_requires_declared_verifier_receipt
#print axioms AgentCore.recorded_verdict_blocks_repeat_verdict_step
#print axioms AgentCore.graph_step_advances_registries
#print axioms AgentCore.graph_step_preserves_acceptance_outstanding
#print axioms AgentCore.graph_reachable_preserves_acceptance_outstanding
#print axioms AgentCore.graph_step_preserves_acceptance_criteria_unique
#print axioms AgentCore.graph_reachable_preserves_acceptance_criteria_unique
#print axioms AgentCore.graph_step_preserves_earned_verdicts
#print axioms AgentCore.graph_reachable_preserves_earned_verdicts
#print axioms AgentCore.graph_step_preserves_snapshot_registry_agreement
#print axioms AgentCore.graph_reachable_preserves_snapshot_registry_agreement
#print axioms AgentCore.settled_run_acceptance_holds_at_current_head
#print axioms AgentCore.graph_reachable_settled_acceptance_holds_at_current_head
#print axioms AgentCore.reachable_attempts_have_guarded_admission
#print axioms AgentCore.mediated_nonattempt_preserves_attempts
#print axioms AgentCore.reachable_attempts_have_exact_issued_permits
#print axioms AgentCore.first_attempt_and_exact_audit_are_one_transition
#print axioms AgentCore.approved_attempt_and_exact_audit_are_one_transition
#print axioms AgentCore.continued_attempt_and_exact_audit_are_one_transition
#print axioms AgentCore.stale_denial_and_exact_audit_are_one_transition
#print axioms AgentCore.attempt_receipt_and_exact_audit_are_one_transition
#print axioms AgentCore.reachable_attempts_have_exact_audits
#print axioms AgentCore.reachable_receipt_ids_are_disjoint
#print axioms AgentCore.reachable_from_preserves_guarded_attempt_admissions
#print axioms AgentCore.permit_issue_requires_exact_authenticated_binding
#print axioms AgentCore.exact_issued_permit_substitution_resistant
#print axioms AgentCore.authentication_requires_exact_target_request
#print axioms AgentCore.missing_target_request_cannot_authenticate
#print axioms AgentCore.restart_invalidates_volatile_authentication
#print axioms AgentCore.reset_invalidates_volatile_authentication
#print axioms AgentCore.reset_preserves_durable_permit_state
#print axioms AgentCore.commit_unknown_before_issue_preserves_state
#print axioms AgentCore.commit_unknown_after_issue_persists_exact_record
#print axioms AgentCore.commit_unknown_before_consume_preserves_state
#print axioms AgentCore.commit_unknown_after_consume_persists_attempt_and_consumption
#print axioms AgentCore.consume_is_exact_requested_authenticated_and_atomic
#print axioms AgentCore.exact_authenticated_permit_substitution_resistant
#print axioms AgentCore.consume_requires_current_fence_and_unexpired
#print axioms AgentCore.expired_permit_cannot_consume
#print axioms AgentCore.changed_target_fence_cannot_consume
#print axioms AgentCore.consumed_nonce_identifies_at_most_one_attempt
#print axioms AgentCore.consumed_nonce_cannot_be_consumed_again
#print axioms AgentCore.reachable_permit_protocol_has_historical_issuance
#print axioms AgentCore.reachable_consumption_has_exact_historical_issuance
#print axioms AgentCore.reachable_issue_uses_exact_target_request
#print axioms AgentCore.reachable_authentication_uses_historically_issued_transport
#print axioms AgentCore.direct_has_no_durable_side_effect
#print axioms AgentCore.mediated_rechecks_current_authority_path
#print axioms AgentCore.approved_execution_uses_persisted_identity
#print axioms AgentCore.replay_deterministic
#print axioms AgentCore.replay_revision

-- Constructive witnesses, one per designated family.
#print axioms AgentCore.Examples.nonvacuous_all_mode_preference
#print axioms AgentCore.Examples.nonvacuous_complete_identity_and_keys
#print axioms AgentCore.Examples.nonvacuous_batch_replay_item_association
#print axioms AgentCore.Examples.nonvacuous_authorized_resolution_issue
#print axioms AgentCore.Examples.nonvacuous_foreign_guest_deny
#print axioms AgentCore.Examples.nonvacuous_direct_nondurable
#print axioms AgentCore.Examples.nonvacuous_mixed_batch_partial
#print axioms AgentCore.Examples.nonvacuous_failed_retry
#print axioms AgentCore.Examples.nonvacuous_same_attempt_supersession
#print axioms AgentCore.Examples.nonvacuous_indeterminate_batch_current_not_terminal
#print axioms AgentCore.Examples.nonvacuous_optional_turn_owner_audit
#print axioms AgentCore.Examples.nonvacuous_live_self_event
#print axioms AgentCore.Examples.nonvacuous_actor_local_typed_audit
#print axioms AgentCore.Examples.nonvacuous_projection_reservation_bridge
#print axioms AgentCore.Examples.nonvacuous_route_delivery
#print axioms AgentCore.Examples.nonvacuous_delivery_local_audit
#print axioms AgentCore.Examples.nonvacuous_pinned_root_writer
#print axioms AgentCore.Examples.nonvacuous_equal_pin_current_merge_heads
#print axioms AgentCore.Examples.nonvacuous_delivery_writer
#print axioms AgentCore.Examples.nonvacuous_system_synthesis_writer
#print axioms AgentCore.Examples.nonvacuous_nonempty_audit_terminal_snapshot
#print axioms AgentCore.Examples.nonvacuous_audit_complete_derived_settled
#print axioms AgentCore.Examples.nonvacuous_acceptance_verdict_wrong_subject
#print axioms AgentCore.Examples.nonvacuous_unsatisfied_acceptance_blocks_settled
#print axioms AgentCore.Examples.nonvacuous_acceptance_satisfied_at_head
#print axioms AgentCore.Examples.nonvacuous_acceptance_verdict_blocks_retry
#print axioms AgentCore.Examples.nonvacuous_acceptance_criteria_reserved_at_open
#print axioms AgentCore.Examples.nonvacuous_child_acceptance_criteria_reserved_at_spawn
#print axioms AgentCore.Examples.nonvacuous_acceptance_verdict_recorded
#print axioms AgentCore.Examples.nonvacuous_acceptance_repeat_verdict_step_rejected
#print axioms AgentCore.Examples.nonvacuous_foreign_verifier_verdict_rejected
#print axioms AgentCore.Examples.nonvacuous_acceptance_completion_step_rejected
#print axioms AgentCore.Examples.nonvacuous_acceptance_verdict_step_advances_registries
#print axioms AgentCore.Examples.nonvacuous_acceptance_obligation_stays_outstanding
#print axioms AgentCore.Examples.nonvacuous_acceptance_open_verdict_trace
#print axioms AgentCore.Examples.nonvacuous_acceptance_invariants_along_trace
#print axioms AgentCore.Examples.nonvacuous_acceptance_verdict_settles_run
#print axioms AgentCore.Examples.nonvacuous_acceptance_settlement_invariants
#print axioms AgentCore.Examples.nonvacuous_settled_acceptance_holds_at_current_head
#print axioms AgentCore.Examples.nonvacuous_request_approve_start_trace
#print axioms AgentCore.Examples.nonvacuous_persisted_approval_continuation
#print axioms AgentCore.Examples.nonvacuous_approval_start_then_continue
#print axioms AgentCore.Examples.nonvacuous_malformed_approval_continuation_rejected
#print axioms AgentCore.Examples.nonvacuous_claim_records_future_expiry
#print axioms AgentCore.Examples.nonvacuous_delegation_containment
#print axioms AgentCore.Examples.nonvacuous_lease_reclaim_and_same_turn_resume
#print axioms AgentCore.Examples.nonvacuous_resolution_deadline_bound
#print axioms AgentCore.Examples.nonvacuous_stale_mediated_denial
#print axioms AgentCore.Examples.nonvacuous_view_replay
#print axioms AgentCore.Examples.nonvacuous_live_deny_override
#print axioms AgentCore.Examples.nonvacuous_guest_elevated_allow_filtered
#print axioms AgentCore.Examples.nonvacuous_role_rematerialization_epoch
#print axioms AgentCore.Examples.nonvacuous_empty_placement_rejected
#print axioms AgentCore.Examples.nonvacuous_source_tier_rejected
#print axioms AgentCore.Examples.nonvacuous_receipt_audit_append
#print axioms AgentCore.Examples.nonvacuous_wrong_turn_rejection
#print axioms AgentCore.Examples.nonvacuous_stale_token_rejection
#print axioms AgentCore.Examples.nonvacuous_stale_self_rejection
#print axioms AgentCore.Examples.nonvacuous_unary_commit_pin_inheritance
#print axioms AgentCore.Examples.nonvacuous_causal_chain_preserved
#print axioms AgentCore.Examples.nonvacuous_nonroot_cause_free_append_impossible
#print axioms AgentCore.Examples.nonvacuous_guarded_attempt_reachability
#print axioms AgentCore.Examples.nonvacuous_canonical_mediated_attempt
#print axioms AgentCore.Examples.nonvacuous_canonical_mediated_attempt_audit_atomic
#print axioms AgentCore.Examples.nonvacuous_distributed_permit_issue_consume
#print axioms AgentCore.Examples.nonvacuous_attempt_permit_evidence
#print axioms AgentCore.Examples.nonvacuous_reset_auth
#print axioms AgentCore.Examples.nonvacuous_expired_permit_cannot_consume
#print axioms AgentCore.Examples.nonvacuous_changed_fence
#print axioms AgentCore.Examples.nonvacuous_commit_unknown_before_after_issue
#print axioms AgentCore.Examples.nonvacuous_commit_unknown_before_after_consume
#print axioms AgentCore.Examples.nonvacuous_distributed_permit_replay_after_restart
#print axioms AgentCore.Examples.nonvacuous_missing_target_request_authentication_fails_closed
#print axioms AgentCore.Examples.nonvacuous_approved_attempt_audit_atomic
#print axioms AgentCore.Examples.nonvacuous_continued_attempt_audit_atomic
#print axioms AgentCore.Examples.nonvacuous_attempt_receipt_audit_atomic
#print axioms AgentCore.Examples.nonvacuous_stale_denial_audit_atomic
#print axioms AgentCore.Examples.nonvacuous_renewal_preserves_turn_and_resolution_deadline
#print axioms AgentCore.Examples.nonvacuous_exact_route_projection
#print axioms AgentCore.Examples.nonvacuous_reachable_route_reservation_consistent
#print axioms AgentCore.Examples.nonvacuous_double_route_reservation_is_inconsistent
#print axioms AgentCore.Examples.nonvacuous_redelivery_of_route_reservation_rejected
#print axioms AgentCore.Examples.nonvacuous_source_reservation_audit_binding
#print axioms AgentCore.Examples.nonvacuous_graph_freshness_rejection
#print axioms AgentCore.Examples.nonvacuous_typed_system_writer_audit
#print axioms AgentCore.Examples.nonvacuous_holder_watermark_inequality
#print axioms AgentCore.Examples.nonvacuous_hostile_tier_publication_rejected
#print axioms AgentCore.Examples.nonvacuous_receipt_id_disjointness_rejection
#print axioms AgentCore.Examples.nonvacuous_abandoned_claim_same_ordinal_recovery
#print axioms AgentCore.Examples.nonvacuous_empty_coherent_terminalization
#print axioms AgentCore.Examples.nonvacuous_unheld_nonterminal_sibling_rejected
#print axioms AgentCore.Examples.nonvacuous_exact_run_pin_sources
#print axioms AgentCore.Examples.nonvacuous_forced_sibling_system_fence
#print axioms AgentCore.Examples.nonvacuous_qualified_principal_identity
#print axioms AgentCore.Examples.nonvacuous_foreign_tenant_principal_never_acts_under
#print axioms AgentCore.Examples.nonvacuous_migrated_old_turn_rejected
#print axioms AgentCore.Examples.nonvacuous_run_admission_reservation
#print axioms AgentCore.Examples.nonvacuous_exact_remote_reservation_epoch
#print axioms AgentCore.Examples.nonvacuous_run_admission_completion
#print axioms AgentCore.Examples.nonvacuous_registry_nonempty_and_completed_frontiers
#print axioms AgentCore.Examples.nonvacuous_invalid_migration_target_rejected
#print axioms AgentCore.Examples.nonvacuous_exact_mediated_run_reservation
#print axioms AgentCore.Examples.nonvacuous_changed_run_registry_epoch_rejected
#print axioms AgentCore.Examples.nonvacuous_reachable_settled_run
#print axioms AgentCore.Examples.nonvacuous_reachable_stale_verdict_not_settled
#print axioms AgentCore.Examples.nonvacuous_reachable_settled_obligations_and_acceptance
#print axioms AgentCore.Examples.nonvacuous_interception_pipeline_run
#print axioms AgentCore.Examples.nonvacuous_interceptor_block_scoped_and_final
#print axioms AgentCore.Examples.nonvacuous_tampered_interception_replay_refused
#print axioms AgentCore.Examples.nonvacuous_interception_replay_item_bridge
#print axioms AgentCore.Examples.nonvacuous_unauthorized_interceptor_never_attributed
#print axioms AgentCore.Examples.nonvacuous_intercepted_observe_escalates_to_mediated
#print axioms AgentCore.Examples.nonvacuous_expired_held_turn_blocks_undo
#print axioms AgentCore.Examples.nonvacuous_fenced_undo_redo_trace
#print axioms AgentCore.Examples.nonvacuous_undo_selects_ancestor_and_redo_restores
#print axioms AgentCore.Examples.nonvacuous_secret_custody_exact_and_repoint_invalidates
#print axioms AgentCore.Examples.nonvacuous_secret_delegation_carrier_is_ref_and_leak_is_unreachable
#print axioms AgentCore.Examples.nonvacuous_content_custody_lifecycle
#print axioms AgentCore.Examples.nonvacuous_content_cross_tenant_grant_admits_resolution
#print axioms AgentCore.Examples.nonvacuous_collected_owned_content_is_unreachable
#print axioms AgentCore.Examples.nonvacuous_materialize_then_reconcile_never_duplicates
#print axioms AgentCore.Examples.nonvacuous_credential_isolated_session_trace
#print axioms AgentCore.Examples.nonvacuous_plaintext_session_state_unreachable
#print axioms AgentCore.Examples.nonvacuous_stale_and_closed_session_rejection
#print axioms AgentCore.Examples.nonvacuous_preview_exposure_lifecycle
#print axioms AgentCore.Examples.nonvacuous_turn_owned_execute_tier
#print axioms AgentCore.Examples.nonvacuous_dynamic_isolate_provenance
#print axioms AgentCore.Examples.nonvacuous_dynamic_only_manifest_placement
#print axioms AgentCore.Examples.nonvacuous_slate_lifecycle

-- Contributions and slots (SPEC §4.2): immutable declarations, exclusive origins,
-- schema-conformant entries, and declared-order arrival-independent resolution.
#print axioms AgentCore.occupied_slot_redeclaration_rejected
#print axioms AgentCore.slot_reinstallation_is_stored_identity
#print axioms AgentCore.slot_step_preserves_declarations
#print axioms AgentCore.uninstalled_slot_contribution_rejected
#print axioms AgentCore.nonvalidating_contribution_rejected
#print axioms AgentCore.conflicting_origin_contribution_rejected
#print axioms AgentCore.entry_id_reuse_rejected
#print axioms AgentCore.recontribution_is_stored_identity
#print axioms AgentCore.slot_step_preserves_origin_exclusivity
#print axioms AgentCore.slot_step_preserves_entry_conformance
#print axioms AgentCore.resolution_is_complete_and_declared_order
#print axioms AgentCore.resolution_ignores_arrival_order
#print axioms AgentCore.resolution_is_unique_declared_order
#print axioms AgentCore.resolved_entry_is_stored_and_validates
#print axioms AgentCore.authorized_slot_step_is_slot_step
#print axioms AgentCore.unauthorized_contributor_never_lands
#print axioms AgentCore.authorized_contribution_carries_admission
#print axioms AgentCore.non_contribute_step_needs_no_authority

-- Commands (SPEC §4.3): per-surface collision rejection, exact derived routes,
-- install-checked mappings, validated invocation input, and submission idempotency.
#print axioms AgentCore.command_surface_collision_rejected
#print axioms AgentCore.occupied_command_id_installation_rejected
#print axioms AgentCore.command_reinstallation_is_stored_identity
#print axioms AgentCore.installation_registers_exact_derived_route
#print axioms AgentCore.nonderived_route_installation_rejected
#print axioms AgentCore.installed_route_is_initiator_with_event_dedupe
#print axioms AgentCore.default_accepted_trust_excludes_external
#print axioms AgentCore.deriveSubscription_matches_derived_route
#print axioms AgentCore.default_derived_subscription_excludes_external
#print axioms AgentCore.empty_trust_installation_rejected
#print axioms AgentCore.unsafe_mapping_installation_rejected
#print axioms AgentCore.uninstalled_command_invocation_rejected
#print axioms AgentCore.invalid_arguments_invocation_rejected
#print axioms AgentCore.command_step_preserves_installed_mapping_safety
#print axioms AgentCore.command_step_preserves_surface_registration
#print axioms AgentCore.invocation_emits_validated_operation_input
#print axioms AgentCore.commit_requires_unreserved_identity
#print axioms AgentCore.reserved_identity_cannot_recommit
#print axioms AgentCore.resubmission_returns_recorded_reply
#print axioms AgentCore.duplicate_submission_reserves_and_emits_nothing
#print axioms AgentCore.duplicate_cites_reserving_original
#print axioms AgentCore.submission_step_preserves_reservation_consistency
#print axioms AgentCore.at_most_one_reserving_write_per_identity

-- The command protocol dispatcher (SPEC §8.5): fixed gate order, duplicate-never-
-- mutates, exactly-one linked WriteRecord and AuditRecord, and the executable mirror.
#print axioms AgentCore.leaseGateBool_eq_true_iff
#print axioms AgentCore.dispatch_appends_exactly_one_linked_write_and_audit
#print axioms AgentCore.dispatch_duplicate_never_mutates
#print axioms AgentCore.dispatch_nonmutating_outcome_preserves_domain
#print axioms AgentCore.dispatch_reserved_identity_only_duplicates
#print axioms AgentCore.dispatch_commit_passed_every_gate
#print axioms AgentCore.dispatchExec_sound
#print axioms AgentCore.dispatchExec_complete

-- Contribution, slot, command, and submission witnesses.
#print axioms AgentCore.Examples.nonvacuous_slot_contribution_lifecycle
#print axioms AgentCore.Examples.nonvacuous_resolution_reorders_arrivals
#print axioms AgentCore.Examples.nonvacuous_arrival_free_resolution
#print axioms AgentCore.Examples.nonvacuous_slot_redeclaration_rejected
#print axioms AgentCore.Examples.nonvacuous_uninstalled_contribution_rejected
#print axioms AgentCore.Examples.nonvacuous_nonvalidating_contribution_rejected
#print axioms AgentCore.Examples.nonvacuous_conflicting_origin_rejected
#print axioms AgentCore.Examples.nonvacuous_entry_id_reuse_rejected
#print axioms AgentCore.Examples.nonvacuous_slot_noop_reinstallation
#print axioms AgentCore.Examples.nonvacuous_prompt_slot_authority_gate
#print axioms AgentCore.Examples.nonvacuous_command_installation_and_validated_invocation
#print axioms AgentCore.Examples.nonvacuous_derived_subscription_exactness
#print axioms AgentCore.Examples.nonvacuous_command_surface_collision_rejected
#print axioms AgentCore.Examples.nonvacuous_occupied_command_id_installation_rejected
#print axioms AgentCore.Examples.nonvacuous_command_reinstallation_identity
#print axioms AgentCore.Examples.nonvacuous_nonderived_route_rejected
#print axioms AgentCore.Examples.nonvacuous_empty_trust_installation_rejected
#print axioms AgentCore.Examples.nonvacuous_unsafe_mapping_installation_rejected
#print axioms AgentCore.Examples.nonvacuous_uninstalled_invocation_rejected
#print axioms AgentCore.Examples.nonvacuous_invalid_arguments_invocation_rejected
#print axioms AgentCore.Examples.nonvacuous_duplicate_submission_is_recorded_evidence
#print axioms AgentCore.Examples.nonvacuous_reserved_identity_recommit_rejected
#print axioms AgentCore.Examples.nonvacuous_double_reservation_is_inconsistent

-- Dispatcher witnesses (SPEC §8.5).
#print axioms AgentCore.Examples.nonvacuous_dispatch_commit_then_duplicate_never_mutates
#print axioms AgentCore.Examples.nonvacuous_dispatchExec_matches_commit_then_duplicate

-- Event → Subscription routing (SPEC §6.2): at-most-once, derived targeting, trust.
#print axioms AgentCore.fire_consumes_key
#print axioms AgentCore.consumed_key_never_refires
#print axioms AgentCore.fire_targets_declared
#print axioms AgentCore.fire_is_tenant_contained
#print axioms AgentCore.fire_admits_channel_trust
#print axioms AgentCore.disabled_never_fires
#print axioms AgentCore.consumed_is_monotone
#print axioms AgentCore.disable_retains_consumed

-- Representation: connected-account broker reduced to the approval ledger.
#print axioms AgentCore.Representation.Broker.initial_custody
#print axioms AgentCore.Representation.Broker.step_preserves_custody
#print axioms AgentCore.Representation.Broker.reachable_custody
#print axioms AgentCore.Representation.Broker.apply_action_gate
#print axioms AgentCore.Representation.Broker.tampered_action_never_fires
#print axioms AgentCore.Representation.Broker.consumed_action_never_refires
#print axioms AgentCore.Representation.Broker.expired_action_never_fires

-- Representation: device-consent gate as per-pair epoch revocation.
#print axioms AgentCore.Representation.Consent.no_grant_denies
#print axioms AgentCore.Representation.Consent.revoke_blocks
#print axioms AgentCore.Representation.Consent.grant_is_per_pair
#print axioms AgentCore.Representation.Consent.execute_requires_live_consent

-- Representation: reaction system reduced to routing dedup and lease fencing.
#print axioms AgentCore.Representation.Reaction.reaction_at_most_once
#print axioms AgentCore.Representation.Reaction.reaction_targets_declared
#print axioms AgentCore.Representation.Reaction.reaction_consumes_key
#print axioms AgentCore.Representation.Reaction.reaction_trust_is_channel_derived
#print axioms AgentCore.Representation.Reaction.stale_injection_rejected
#print axioms AgentCore.Representation.Reaction.wrong_turn_injection_rejected
#print axioms AgentCore.Representation.Reaction.expired_injection_rejected

-- Representation: mixture-of-agents aggregation chains over binary merges.
#print axioms AgentCore.Representation.MixtureOfAgents.aggregate_recorded
#print axioms AgentCore.Representation.MixtureOfAgents.proposers_are_ancestors
#print axioms AgentCore.Representation.MixtureOfAgents.root_is_ancestor
#print axioms AgentCore.Representation.MixtureOfAgents.proposers_are_single_run
#print axioms AgentCore.Representation.MixtureOfAgents.chain_preserves_pins

-- Routing and representation nonvacuity witnesses.
#print axioms AgentCore.Examples.nonvacuous_subscription_fires
#print axioms AgentCore.Examples.nonvacuous_redelivery_is_inert
#print axioms AgentCore.Examples.nonvacuous_same_event_never_refires
#print axioms AgentCore.Examples.nonvacuous_disabled_subscription_rejected
#print axioms AgentCore.Examples.nonvacuous_broker_available
#print axioms AgentCore.Examples.nonvacuous_broker_apply_action
#print axioms AgentCore.Examples.nonvacuous_aggregation_chain
#print axioms AgentCore.Examples.nonvacuous_consent_grant_is_live
#print axioms AgentCore.Examples.nonvacuous_consent_revocation_blocks
#print axioms AgentCore.Examples.nonvacuous_midturn_stale_injection_rejected

-- Executable lease semantics: the differential oracle's answers carry the relation.
#print axioms AgentCore.leaseStepExec_sound
#print axioms AgentCore.leaseStepExec_complete
