/*
 * Generated by TSLean from a kernel-checked Lean declaration.
 * Fragment: tslean-structural-first-order-v4
 * Source module: AgentCore.Facets.Enforcement
 * Semantic identity: sha256:eb1773a0680b94451927b632f713128fc069ce8d809834c9255b9cad3c53123d
 * Input closure: sha256:dca07c0c62447c349182cbfac1b405e4f270ce91b8bbec37fae1a719dff9c700
 * Semantic IR: sha256:e2e0e309931ee47d70c6f6a7930e3c9a14e32964f80280cc50aa8ea41eaaad4b
 * Generated body: sha256:b3221ed478a774ea669388799a9b2e03566d3734b232befcdc258b7925d3d309
 * Lean toolchain: leanprover/lean4:v4.29.0
 * Lean: Lean (version 4.29.0, x86_64-unknown-linux-gnu, commit 98dc76e3c0a9b856c9b98726b713fb04fab16740, Release)
 * Lake: Lake version 5.0.0-src+98dc76e (Lean version 4.29.0)
 * Environment attestation: recorded in the manifest sidecar; it does not affect these bytes.
 * Evidence boundary: generation is checked and differential tests are empirical; no refinement theorem is claimed.
 */
/**
 * Which enforcement tier serves a call (SPEC §7.2). Only `mediated` carries evidence: a
 * direct call performs its authority, lease, watermark, PathEpochEvidence, and deadline
 * checks in memory and writes nothing durable, so there is no Invocation for it to name.
 */
export type EnforcementTier = "direct" | "mediated";

/**
 * The impact an Operation declares, and the seam its request crosses (SPEC §4.2, §7.1).
 * The host derives impact from the seam, never from what the callee claims about itself.
 */
export type Impact = "observe" | "mutate" | "externalSend" | "execute" | "delegate" | "administer";

/**
 * Whether this impact may ever be served directly (SPEC §7.2): `observe` always may;
 * `execute` only inside a Turn-owned Session; `mutate` only against that Session's own
 * filesystem; `externalSend`, `delegate`, and `administer` never may.
 */
function admitsDirect(impact: Impact, turnOwnedSession: boolean, sessionFilesystemTarget: boolean): boolean {
    return impact === "observe" ? true : impact === "mutate" ? turnOwnedSession && sessionFilesystemTarget : impact === "externalSend" ? false : impact === "execute" ? turnOwnedSession : impact === "delegate" ? false : false;
}

/**
 * Whether a claim honors the derived impact's floor under one fixed session condition: the
 * claim is admissible unless it would be served directly where the derived impact would
 * have been mediated.
 */
function honorsFloorUnder(claimed: Impact, derived: Impact, turnOwnedSession: boolean, sessionFilesystemTarget: boolean): boolean {
    return !admitsDirect(claimed, turnOwnedSession, sessionFilesystemTarget) || admitsDirect(derived, turnOwnedSession, sessionFilesystemTarget);
}

/**
 * SPEC §7.1 (C13-POLICY-IMPACT-BOUNDARY): a callee's own claim may replace the derived
 * impact only when it never admits a floor (§7.2) the derived impact would have mediated.
 * Checked under both Turn-owned-Session conditions, because a claim recorded once — at
 * discovery or install time — has to hold safe at every call site it is later used at.
 * `sessionFilesystemTarget` is fixed per caller: pass `false` for a seam whose target is
 * never a Turn-owned Session's own filesystem.
 */
export function claimHonorsEnforcementFloor(claimed: Impact, derived: Impact, sessionFilesystemTarget: boolean): boolean {
    return honorsFloorUnder(claimed, derived, true, sessionFilesystemTarget) && honorsFloorUnder(claimed, derived, false, sessionFilesystemTarget);
}

/**
 * SPEC §7.2's enforcement floor: the weakest tier this impact admits under the given
 * session conditions. Policy only tightens this floor; it never lowers it.
 */
export function enforcementFloor(impact: Impact, turnOwnedSession: boolean, sessionFilesystemTarget: boolean): EnforcementTier {
    return admitsDirect(impact, turnOwnedSession, sessionFilesystemTarget) ? "direct" : "mediated";
}
