import { cp, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { afterEach, describe, expect, test } from "vitest";
import { runQualitySubprocess, subprocessTestOptions } from "./subprocess";

const packageRoot = resolve(import.meta.dirname, "../..");
const checker = resolve(packageRoot, "scripts/quality/tslean-consumer.mjs");
const generatedModule = "src/facets/generated/AgentCore/Facets/Enforcement.ts";
const committedModule = await readFile(resolve(packageRoot, generatedModule), "utf8");
const temporary: string[] = [];

afterEach(async () => {
    await Promise.all(
        temporary.splice(0).map((path) => rm(path, { recursive: true, force: true }))
    );
});

// The gate reads the repository it sits in, so every case is a scratch copy of the real
// tree with exactly one byte-level defect introduced. The copies share nothing with the
// worktree: a case that mutated the committed artifact in place would leave the gate's own
// input dirty for whichever test ran after it.
async function scratchTree() {
    const root = await mkdtemp(join(tmpdir(), "tslean-consumer-"));
    temporary.push(root);
    await cp(packageRoot, root, {
        recursive: true,
        filter: (source) =>
            !["node_modules", "reports", ".git", "dist"].includes(source.split("/").pop() ?? "")
    });
    return root;
}

describe("the TSLean consumer gate", subprocessTestOptions, () => {
    test("accepts the committed generated package offline", () => {
        const result = runQualitySubprocess(
            process.execPath,
            [checker, "--stage", "building"],
            packageRoot
        );
        expect(result.status, result.stderr).toBe(0);
        expect(result.stdout).toContain("tslean consumer verified");
    });

    test("refuses a tampered generated byte", async () => {
        const root = await scratchTree();
        const tampered = committedModule
            .split("return turnOwnedSession && sessionFilesystemTarget;")
            .join("return turnOwnedSession || sessionFilesystemTarget;");
        if (tampered === committedModule) throw new TypeError("tamper fixture located nothing");
        await writeFile(join(root, generatedModule), tampered, "utf8");

        const result = runQualitySubprocess(
            process.execPath,
            [join(root, "scripts/quality/tslean-consumer.mjs"), "--stage", "building"],
            root
        );
        expect(result.status).toBe(1);
        expect(result.stderr).toContain("generated TSLean package is not intact");
        expect(result.stderr).toContain(
            "generated module body does not hash to its manifest digest"
        );
    });

    test("refuses a committed Lean source the manifest no longer describes", async () => {
        const root = await scratchTree();
        const leanPath = join(root, "formal/AgentCore/Facets/Enforcement.lean");
        const lean = await readFile(leanPath, "utf8");
        const drifted = lean.split("| .observe => true").join("| .observe => false");
        if (drifted === lean) throw new TypeError("drift fixture located nothing");
        await writeFile(leanPath, drifted, "utf8");

        const result = runQualitySubprocess(
            process.execPath,
            [join(root, "scripts/quality/tslean-consumer.mjs"), "--stage", "building"],
            root
        );
        expect(result.status).toBe(1);
        expect(result.stderr).toContain("manifest Lean source digest");
        expect(result.stderr).toContain("does not match committed");
    });

    test("refuses a manifest that blesses bytes the compiler never produced", async () => {
        const root = await scratchTree();
        const tampered = committedModule
            .split("return turnOwnedSession && sessionFilesystemTarget;")
            .join("return turnOwnedSession || sessionFilesystemTarget;");
        if (tampered === committedModule) throw new TypeError("tamper fixture located nothing");
        await writeFile(join(root, generatedModule), tampered, "utf8");
        // Re-bless the tampered bytes into the manifest's own digest fields, so the only
        // thing that can refuse them is the provenance header the semantic identity still
        // demands at the top of the file.
        const manifestPath = join(root, "src/facets/generated/tslean.manifest.json");
        const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
        const record = manifest.semantic.modules.find(
            (module: { path: string }) => module.path === "AgentCore/Facets/Enforcement.ts"
        );
        record.bodySha256 =
            "sha256:" +
            (await import("node:crypto"))
                .createHash("sha256")
                .update(tampered.slice(record.bodySha256.length))
                .digest("hex");
        await writeFile(manifestPath, JSON.stringify(manifest, null, 2), "utf8");

        const result = runQualitySubprocess(
            process.execPath,
            [join(root, "scripts/quality/tslean-consumer.mjs"), "--stage", "building"],
            root
        );
        expect(result.status).toBe(1);
        expect(result.stderr).toContain("generated TSLean package is not intact");
        expect(result.stderr).toContain("provenance header does not match its manifest");
    });
});
